import 'package:bliksy/Localization/save_locale.dart';
import 'package:get/get.dart';

class LocLizationClass extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'welcomeText': 'Welcome to BLIKSY rider.',
          'home':'Home',
          'orderHome':'My Order',
          'earning':'Earnings',
          'bliksy': 'BLIKSY',
          'otpCode': 'OTP Code',
          'loginRiderAccountTxt': 'Login into rider account',
          'phoneNumb': 'Phone number',
          'termsConditionTxt':
              'We will send you verification code. Message and data rates may apply. By continuing, you agree to our',
          'terms': ' Terms of services',
          'andSign': '& ',
          'privacyPloicy': 'privacy policy.',
          'continueTxt': 'Continue',
          'notRiderTxt': 'Not yet a rider?',
          'becomePartner': 'Become Bliksy partner',
          'createAnAccountTxt': 'Create an account',
          'stepsTxt': 'Steps 1 of ',
          'fullNameTxt': 'Full name',
          'emailTxt': 'Email address',
          'dob':'Date of birth',
          'city': 'Home address',
          'cityName': 'home,street,address,postalcode',
          'password':'Password',
          'passwordTxt': 'Enter a password',
          'enterOtpTxt':
              'Enter the OTP code we send via SMS to \nyour registered phone number',
          'didNotGetOtp': 'Didn’t get the OTP?',
          'resend': 'Resend',
          'backText': 'Back',
          'drivingLicenseTxt': 'Driving License',
          'drivingLicensImg': 'Driving License Image',
          'hereAboutBliksyTxt': 'How did you hear about BLIKSY',
          'socialMediaTxt': 'Social Media',
          'websiteTxt': 'Website',
          'viaAqTxt': 'Via acquaintance (s)',
          'otherTxt': 'Other',
          'onlineTxt': 'Online',
          'homeTxt': 'Home',
          'orderTxt': 'Order',
          'earningsTxt': 'Earnings',
          'cancelOrderTxt': 'Cancel Order',
          'pickUpTxt': 'Pickup from',
          'deliveryto': 'Delivery to',
          'orderTypeTxt': 'Order Type',
          'orderAmountTxt': 'Order Amount',
          'earningAmount': 'Earning Amount',
          'acceptOrderTxt': 'Accept Order',
          'myEarningTxt': 'My Earnings',
          'walletBalanceTxt': 'Wallet Balance',
          'withDrawTxt': 'WITHDRAW',
          'totalOrder': 'Total Orders',
          'totalOnlineTxt': 'Total Online',
          'totalDistanceTxt': 'Total Distance',
          'orderEarningsTxt': 'Orders Earning',
          'tpisTxt': 'Tips',
          'totalEarningsTxt': 'Total Earnings',
          'orderDetail': 'Order details:',
          'cash': 'Cash',
          'orderDe': 'Order\'s Details',
          'deliverOrder': 'Deliver order',
          'collectOrder': 'Collect order',
          'cancelOrder': 'Cancel order',
          'storeIns': 'Store\'s instruction',
          'pickUpfrom':'Pickup from curbside',
          'order':'Order#',
          'orderDetails': 'Order\'s details',
          'tickToContinueBtnTxt':'Tick order to continue',
          'deliveryIns':'Delivery instructions',
          'noContentDelivery':'No content delivery',
          'deliveryMessage':'Please drop at bench near to my gate',
          'takePhoto':'Take a photo',
          'deliveryMsg':'Take a photo showing  where you are left the\n order. We\'ll save the as a proof of delivery',
          'tapClickPhoto':'Tap and click the photo',
          'completeMyOrder':'Complete my order',
          'rateYourExp': 'Rate your experience',
          'addYourReviwe': 'Add your review',
          'tapAddReview': 'Tap and add your review',
          'viewProfile': 'View Profile',
          'notification': 'Notification',
          'settings': 'Settings',
          'card': 'Card',
          'myOrder': 'My Order',
          'changeMyVehicle': 'Change my vehicle',
          'changeMyLanguage': 'Change my language',
          'chooseLanguage': 'Choose language',
          'englishLang': 'English',
          'dutchLang': 'Dutch',
          'about': 'About',
          'sendfeedback': 'Send feedback',
          'rateus': 'Rate us',
          'inviteFriend': 'Invite Friends',
          'logout': 'Logout',
          'myOrders': 'My Orders',
          'onGoingOrder': 'Ongoing',
          'completedOrder': 'Completed',
          'workingarea': 'Working area',
          'current': 'Current',
          'nearby': 'Nearby',
          'update': 'Update',

        },
  
        'nl_NL':{
          'welcomeText': 'Welkom bij BLIKSY-rijder.',
          'bliksy': 'BLIKSY',
          'otpCode': 'OTP-code',
          'home':'huis',
          'orderHome':'Mijn bestelling',
          'earning':'Inkomsten', 
          'loginRiderAccountTxt': 'Log in op rijdersaccount',
          'phoneNumb': 'Telefoonnummer',
          'termsConditionTxt':
              'We sturen je een verificatiecode. Bericht- en datatarieven kunnen van toepassing zijn. Door verder te gaan, gaat u akkoord met onze',
          'terms': ' Servicevoorwaarden',
          'andSign': '& ',
          'privacyPloicy': 'privacybeleid.',
          'continueTxt': 'Doorgaan',
          'notRiderTxt': 'Nog geen ruiter?',
          'becomePartner': 'Word Bliksy-partner',
          'createAnAccountTxt': 'Een account aanmaken',
          'stepsTxt': 'Stap 1 van',
          'fullNameTxt': 'Voornaam + Achternaam',
          'emailTxt': 'E-mail adres',
          'dob':'Geboortedatum',
          'city': 'Plaatsnaam',
          'cityName': 'Adress/Adres, House number/Huisnummer, Postal code/Postcode',
          'password':'Wachtwoord',
          'passwordTxt': 'Voer een wachtwoord in',
          'enterOtpTxt':
              'Vul de verificatiecode in die je per\nSMS hebt ontvangen',
          'didNotGetOtp': 'Verificatiecode niet ontvangen?',
          'resend': 'Opnieuw sturen',
          'backText': 'Terug',
          'drivingLicenseTxt': 'Rijbewijsnummer',
          'drivingLicensImg': 'Rijbewijs Afbeelding',
          'hereAboutBliksyTxt': 'Waar ken je BLIKSY van?',
          'socialMediaTxt': 'Social Media',
          'websiteTxt': 'Website',
          'viaAqTxt': 'Vrienden',
          'otherTxt': 'Anders',
          'onlineTxt': 'Online',
          'homeTxt': 'Huis',
          'orderDetails': 'Details van de bestelling',
          'earningsTxt': 'Inkomsten',
          'cancelOrderTxt': 'Annuleer bestelling',
          'pickUpTxt': 'Afhalen bij',
          'deliveryto': 'Bezorgadres',
          'orderTypeTxt': 'Betaalmethode:',
          'orderAmountTxt': 'Bestelbedrag',
          'earningAmount': 'Verdiensten',
          'acceptOrderTxt': 'Rit Bevestigen',
          'myEarningTxt': 'mijn Inkomens',
          'walletBalanceTxt': 'Wallet-saldo',
          'withDrawTxt': 'TERUGTREKKEN',
          'totalOrder': 'Totaal aantal bestellingen',
          'totalOnlineTxt': 'Totaal online',
          'totalDistanceTxt': 'Totale afstand',
          'orderEarningsTxt': 'Bestellingen verdienen',
          'tpisTxt': 'Tips',
          'totalEarningsTxt': 'totale winst',
          'orderDetail': 'Bestel Details:',
          'cash': 'Contant geld',
          'orderDe': 'Bestellingnummer',
          'deliverOrder': 'Bezorg bestelling',
          'collectOrder': 'Bestelling ophalen',
          'cancelOrder': 'Annuleer bestelling',
          'storeIns': 'Instructies voor pick-up',
          'pickUpfrom':'Opmerkingen',
          'order':'Bestellen#',
          'tickToContinueBtnTxt':'Vink het doosje aan om door te gaan',
          'deliveryIns':'Bezorg instructies',
          'noContentDelivery':'Contactloze bezorging',
          'deliveryMessage':'Opmerkingen',
          'takePhoto':'Maak een foto',
          'deliveryMsg':'Maak een foto van waar je de bestelling\n hebt achtergelaten. Deze bewaren wij als bewijs van bezorging',
          'tapClickPhoto':'Tik en maak foto',
          'completeMyOrder':'Rit beëindigen',
          'rateYourExp': 'Beoordeel je ervaring',
          'tapAddReview': 'Klik en plaats review',
          'addYourReviwe': 'Review plaatsen',
          'viewProfile': 'Profiel bekijken',
          'notification': 'Kennisgeving',
          'settings': 'Instellingen',
          'card': 'Kaart',
          'myOrder': 'Mijn bestelling',
          'changeMyVehicle': 'Mijn voertuig wijzigen',
          'changeMyLanguage': 'Mijn taal wijzigen',
          'chooseLanguage': 'Kies een taal',
          'englishLang': 'Engels',
          'dutchLang': 'Nederlands',
          'about': 'Over',
          'sendfeedback': 'Feedback verzenden',
          'rateus': 'Beoordeel ons',
          'inviteFriend': 'Nodig vrienden uit',
          'logout': 'Uitloggen',
          'myOrders': 'mijn bestellingen',
          'onGoingOrder' : 'Voortdurende',
          'completedOrder': 'Voltooid',
          'workingarea': 'Werkgebied',
          'current': 'Huidig',
          'nearby': 'Dichtbij',
          'update': 'Update',
        
        }
      };
}
